mqtt: 
    brokerHostAndPort: tcp://127.0.0.1:1883
    id: gateway
    userName: admin
    passWord: admin
    is-mqtt-client: true
netty: 
    client:
        id: testID1
        server-ip: 0.0.0.0
        server-port: 54321
    is-client: true
device: 
    allow-id: device-1,device-2