server:
    port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 112233
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    generate-ddl: true 
    show-sql: true
    properties:
        hibernate:
            format_sql: false
  thymeleaf:
    prefix: classpath:/templates/
    cache: false


